locals {
  regions = {
    brazilsouth         = "zb1"
    eastus              = "zu1"
    eastus2             = "zu2"
    southcentralus      = "qu1"
    westus2             = "wu2"
    westus3             = "wu3"
    northeurope         = "neu"
    swedencentral       = "scd"
    uksouth             = "suk"
    westeurope          = "weu"
    centralus           = "cu1"
    francecentral       = "frc"
    germanywestcentral  = "gex"
    italynorth          = "itn"
    norwayeast          = "noe"
    polandcentral       = "poc"
    switzerlandnorth    = "szn"
    northcentralus      = "yu1"
    westus              = "wu1"
    westcentralus       = "xu1"
    francesouth         = "frs"
    germanynorth        = "gen"
    norwaywest          = "now"
    switzerlandwest     = "szw"
    ukwest              = "wuk"
    centralindia        = "cin"
    canadaeast          = "cne"
  }
}